# Generated by Django 4.2.7 on 2023-11-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IT Infrastructure", "IT"),
                            ("Software Development", "SDE"),
                            ("Consultancy", "HR"),
                            ("Banking", "Banking"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact", models.IntegerField()),
                ("active", models.BooleanField(default=False)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(max_length=256)),
            ],
        ),
    ]
