# Generated by Django 4.2.7 on 2023-11-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "emp_type",
                    models.CharField(
                        choices=[
                            ("PT", "Permanent"),
                            ("PR", "Probhiton"),
                            ("C", "Contractiual"),
                            ("T", "Temp"),
                        ],
                        max_length=10,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("salary", models.IntegerField(max_length=100000)),
                ("emp_id", models.IntegerField(max_length=999999999999)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
